### PR TITLE
do not count metadata map in table header as a column

### PR DESCRIPTION
**Pull request by shaunlebron**
found a small bug in the rendering of the [table examples](https://github.com/yogthos/clj-pdf#table)

before and after:
 

I tried running the tests, but it's dumping binary characters in my mac terminal...

### CODE REVIEW

**Comment by yogthos** [comment]
Great thanks for the pr, the tests are just a sanity check since you end up with a binary file. So all you can tell is whether the generated file is the same or not. The output itself is not terribly useful.

**Comment by yogthos** [comment]
I'll push out a new release tonight

**Comment by shaunlebron** [comment]
thanks, this library is awesome

**Comment by yogthos** [comment]
glad to hear it, and the latest version with the fix should be up on Clojars :)

**Pull request merged**
