### PR TITLE
Add type hints to fix reflection warnings

### PR DESCRIPTION
**Pull request by rm-hull**
Various type hints to fix some/most of the reflection warnings as described in issue #62.

### CODE REVIEW

**Comment by yogthos** [comment]
should I push out a new release, or is there anything else you'd like to add before that?

**Comment by rm-hull** [comment]
Not going to get much chance to look at anything else til the weekend, but would like to try and squash the remaining warnings

**Comment by yogthos** [comment]
let me push this one out, and then we can always cut a new release with the warning fixes

**Comment by yogthos** [comment]
also looks like we've got some out of date dependencies:

```
[dom4j "20040902.021138"] is available but we use "1.6.1"
[org.jfree/jfreechart "1.0.19"] is available but we use "1.0.15"
[org.apache.xmlgraphics/batik-gvt "1.8"] is available but we use "1.7"
[midje "1.8.3"] is available but we use "1.7.0"
[environ "1.0.1"] is available but we use "0.5.0"
[midje-readme "1.0.9"] is available but we use "1.0.8"
```

but probably need to do a bit of testing there

**Comment by yogthos** [comment]
latest dom4j and batik-gvt break it, but jfreechart looks like it should be ok, although I'm not sure if we have tests for it

**Comment by rm-hull** [comment]
I think the example.pdf generation tests some aspects of the charting, and one of the projects I use clj-pdf for produces lots of pages of charts (admittedly mostly all the same) - and I tried it with the latest jfreechart point-release - seems to work fine.

I even ran it through with [lein-cloverage](https://github.com/lshift/cloverage) - which is a great tool - and got the following (not unreasonable) coverage stats:

image

**Pull request merged**
