### PR TITLE
Maven fix

### PR DESCRIPTION
**Pull request by coyotespike**
Using AshtonKem's comment, I updated the dependency and reference.

### CODE REVIEW

**Comment by yogthos** [comment]
looks good

**Comment by yogthos** [comment]
the test still fail with the pr though

**Comment by yogthos** [comment]
oh and you can't use iText past version 4.2.1 because the license changed from LGPL to AGPL, it looks like the 4.2.1 jars are actually missing from the central maven repo now http://mvnrepository.com/artifact/com.lowagie/itext/4.2.1

**Comment by yogthos** [comment]
it looks like I may have to build [this version](https://github.com/ymasory/iText-4.2.0) using lein and publish it to Clojars instead

**Comment by coyotespike** [comment]
Sorry, when I said I tested it, I just meant it compiled for me! Thanks for jumping on this.

**Pull request merged**
